### ISSUE TITLE
[Modelina] Add support for Python 3.x

### ISSUE THREAD

**Issue by avineshwar** [asyncapi/modelina#975] opened 2022-10-26 18:33 UTC
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
- How will this change help?
- What is the motivation? 

#### Description
Please try answering few of those questions
- What changes have to be introduced?
- Will this be a breaking change?
- How could it be implemented/designed?

**Comment by jonaslagoni** [comment] 2022-10-26 19:00
@avineshwar [have you checked out the `next` version](https://github.com/asyncapi/modelina/tree/next/examples/generate-python-models)?

If you have, do you mind clarifying how the current python output is insufficient to your liking?

**Comment by zaytsevand** [comment] 2022-10-28 14:22
I guess it's about Implicit-related imports which will not work with Python 3.3+:
[PEP-328](https://peps.python.org/pep-0328/#guido-s-decision)
[Changed in version 3.3](https://docs.python.org/3/reference/import.html)

**Comment by jonaslagoni** [comment] 2022-10-28 17:30
That should be manageable, we also have different import ways for TypeScript.

**Comment by zaytsevand** [comment] 2022-10-31 11:40
> That should be manageable, we also have different import ways for TypeScript.

Could you please suggest a proper way to implement an import differently?
My dumb take on the issue is:
```typescript
        const models = await generator.generateCompleteModels(spec, {});
        const libraryDependencies = new Set(models.flatMap(m => m.dependencies));

        for (const model of models) {
            await writeFile(`${outputDirectory}/${model.modelName}.py`,
                model.result
                    .split('\n')
                    .map(s => {
                        if (libraryDependencies.has(s)) {
                            return s;
                        }
                        if (s.startsWith('from ')) {
                            return s.replace('from ', 'from .');
                        }
                        return s;
                    })
                    .map(s => `${s}\n`)
                    .filter(s => s !== '\n'));
```
1. If it's a library dep, skip it altogether. Unfortunately here, I'm working with dependencies on an import statement level, not with package names (which would be a much better alternative)
2. If it's any other import, then prefix it with a dot, assuming that here we won't receive anything but local imports

**Comment by jonaslagoni** [comment] 2022-10-31 13:27
If the `generateCompleteModels` function does not generate accurate imports, then we should change how it renders dependencies.

Do you have a suggestion for an option you can provide with the function? That we can use inside the python renderer to render appropriate dependencies?

**Comment by zaytsevand** [comment] 2022-10-31 17:25
@jonaslagoni please check the attached PR. Hope that would do

**Comment by jonaslagoni** [comment] 2022-11-09 11:47
I am gonna close this issue for now as a fix is in place.

Feel free to reopen @avineshwar if you don't find it solved it.

**Closed by jonaslagoni** 2022-11-09 11:47 UTC
Labels: enhancement
