### ISSUE TITLE
Typescript generator interface output

### ISSUE THREAD

**Issue by fswebteam** [asyncapi/modelina#1419] opened 2023-06-23 14:04 UTC
#### Describe the bug
The typescript generator, when using `modelType: 'interface'` and `moduleSystem: 'ESM'` does not properly generate models for array with items.

Additional bug - default TS template does creates issue with `verbatimModuleSyntax` setting, as imports  should be with done with type only import, and `export default` should reference a value.

#### How to Reproduce

```
{
  "asyncapi": "2.6.0",
  "info": {
    "title": "Test API",
    "version": "1.0.0"
  },
  "channels": {
    "/": {
      "publish": {
        "operationId": "publish",
        "message": {
          "oneOf": [
            {
              "$ref": "#/components/messages/TestMessage"
            }
          ]
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Item": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "prop1": {
            "type": "number"
          }
        },
        "required": [
          "prop1"
        ]
      },
      "ItemArr": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Item"
        }
      }
    },
    "messages": {
      "TestMessage": {
        "name": "testmessage",
        "payload": {
          "$ref": "#/components/schemas/ItemArr"
        }
      }
    }
  }
}
```

Using above `async.json` either from command line tool, or in online modelina playground, will generate below files:

```ts
# Item.ts

interface Item {
  prop1: number;
}
export default Item;
```
```ts
# ItemArr.ts

import Item from './Item';
type ItemArr = (Item | any)[];
export default ItemArr;
```

Clearly the type for `ItemArr` allows to much, as it should only allow Item types.

#### Expected behavior
The expected output for this output would be:

```ts
# Item.ts

export interface Item {
  prop1: number;
}
```
```ts
# ItemArr.ts

import type { Item } from './Item';
export type ItemArr = Item[];
```

Thanks to this approach the generated complies with `verbatimModuleSyntax` and keeps proper type for the array items.

**Comment by jonaslagoni** [comment] 2023-06-23 14:09
@fswebteam try use the `next` version, it should have been cleared up there.

**Comment by jonaslagoni** [comment] 2023-06-24 21:47
Duplicate of #1416

**Closed by jonaslagoni** 2023-06-24 21:47 UTC
Labels: bug
